import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="w-[310px] fixed overflow-y-auto shadow-xl">
            <SideBar />
          </div>
          <div className="w-full ml-[310px] px-12">
            <div className="flex flex-col">
              <Header />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
